# ==============================================
# SPRING BOOT GENERAL CONFIG
# ==============================================
server.port=8080
==========================
# ASTRA DB (Using Secure Connect Bundle)
# ==============================================
spring.data.cassandra.config=classpath:secure-connect-bundle.zip
spring.data.cassandra.username=token
spring.data.cassandra.password=${ASTRA_TOKEN}
spring.data.cassandra.keyspace=${ASTRA_KEYSPACE}
spring.data.cassandra.schema-action=CREATE_IF_NOT_EXISTS
spring.data.cassandra.request.timeout=10000
